/* MER - Lógico Faculdade DB: */

CREATE TABLE DEPARTAMENTO (
    cod_depto INT PRIMARY KEY,
    nome_depto CHARACTER
);

CREATE TABLE PROFESSOR (
    cod_professor INT PRIMARY KEY,
    FK_DEPARTAMENTO_cod_depto INT,
    nome_prof CHARACTER,
    sobrenome_prof CHARACTER,
    status BOOLEAN
);

CREATE TABLE PROF_DISCIPLINA (
    FK_PROFESSOR_cod_professor INT,
    FK_DISCIPLINA_cod_disciplina INT
);

CREATE TABLE DISCIPLINA (
    cod_disciplina INT PRIMARY KEY,
    FK_DEPARTAMENTO_cod_depto INT,
    num_alunos INT,
    nome_disciplina CHARACTER,
    carga_horaria INT,
    descricao CHARACTER
);

CREATE TABLE CURSO (
    cod_curso INT PRIMARY KEY,
    FK_DEPARTAMENTO_cod_depto INT,
    nome_curso CHARACTER
);

CREATE TABLE TURMA (
    cod_turma INT PRIMARY KEY,
    FK_CURSO_cod_curso INT,
    data_inicio DATE,
    data_fim DATE,
    periodo INT,
    num_alunos INT
);

CREATE TABLE ALUNO (
    RA CHARACTER PRIMARY KEY,
    FK_CURSO_cod_curso INT,
    FK_TURMA_cod_turma INT,
    sexo CHARACTER,
    CPF CHARACTER,
    sobrenome CHARACTER,
    nome CHARACTER,
    status CHARACTER,
    semestre_atual CHARACTER,
    nome_pai CHARACTER,
    nome_mae CHARACTER,
    email CHARACTER,
    whatsapp CHARACTER
);

CREATE TABLE DISC_HIST (
    FK_DISCIPLINA_cod_disciplina INT,
    FK_HISTORICO_cod_historico INT
);

CREATE TABLE CURSO_DISCIPLINA (
    FK_CURSO_cod_curso INT,
    FK_DISCIPLINA_cod_disciplina INT
);

CREATE TABLE ALUNO_DISCP (
    FK_DISCIPLINA_cod_disciplina INT,
    FK_ALUNO_HISTORICO_RA CHARACTER
);

CREATE TABLE HISTORICO (
    cod_historico INT NOT NULL PRIMARY KEY,
    RA CHARACTER,
    data_inicio DATE,
    data_final DATE
);

CREATE TABLE DEPENDE (
    fk_DISCIPLINA_cod_disciplina INT,
    fk_DISCIPLINA_cod_disciplina_ INT
);

CREATE TABLE TEL_ALUNO (
    cod_tel_alunos INT PRIMARY KEY,
    RA CHARACTER
);

CREATE TABLE TIPO_TEL (
    cod_tipo_tel INT PRIMARY KEY,
    tipo_tel CHARACTER
);

CREATE TABLE ENDERECO (
    cod_endereco_aluno INT PRIMARY KEY,
    nome_rua CHARACTER,
    num_rua INT,
    complemento CHARACTER,
    CEP CHARACTER,
    RA CHARACTER
);

CREATE TABLE ALUNO_TEL (
    cod_tel_alunos INT,
    RA CHARACTER,
    PRIMARY KEY (cod_tel_alunos, RA)
);
 
ALTER TABLE PROFESSOR ADD CONSTRAINT FK_PROFESSOR_2
    FOREIGN KEY (FK_DEPARTAMENTO_cod_depto)
    REFERENCES DEPARTAMENTO (cod_depto)
    ON DELETE RESTRICT;
 
ALTER TABLE PROF_DISCIPLINA ADD CONSTRAINT FK_PROF_DISCIPLINA_1
    FOREIGN KEY (FK_PROFESSOR_cod_professor)
    REFERENCES PROFESSOR (cod_professor)
    ON DELETE CASCADE;
 
ALTER TABLE PROF_DISCIPLINA ADD CONSTRAINT FK_PROF_DISCIPLINA_2
    FOREIGN KEY (FK_DISCIPLINA_cod_disciplina)
    REFERENCES DISCIPLINA (cod_disciplina)
    ON DELETE RESTRICT;
 
ALTER TABLE DISCIPLINA ADD CONSTRAINT FK_DISCIPLINA_2
    FOREIGN KEY (FK_DEPARTAMENTO_cod_depto)
    REFERENCES DEPARTAMENTO (cod_depto)
    ON DELETE RESTRICT;
 
ALTER TABLE CURSO ADD CONSTRAINT FK_CURSO_2
    FOREIGN KEY (FK_DEPARTAMENTO_cod_depto)
    REFERENCES DEPARTAMENTO (cod_depto)
    ON DELETE RESTRICT;
 
ALTER TABLE TURMA ADD CONSTRAINT FK_TURMA_2
    FOREIGN KEY (FK_CURSO_cod_curso)
    REFERENCES CURSO (cod_curso)
    ON DELETE CASCADE;
 
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_2
    FOREIGN KEY (FK_telefone_telefone_PK)
    REFERENCES HISTORICO (cod_historico)
    ON DELETE NO ACTION;
 
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_3
    FOREIGN KEY (FK_CURSO_cod_curso)
    REFERENCES CURSO (cod_curso)
    ON DELETE CASCADE;
 
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_4
    FOREIGN KEY (FK_TURMA_cod_turma)
    REFERENCES TURMA (cod_turma)
    ON DELETE RESTRICT;
 
ALTER TABLE DISC_HIST ADD CONSTRAINT FK_DISC_HIST_1
    FOREIGN KEY (FK_DISCIPLINA_cod_disciplina)
    REFERENCES DISCIPLINA (cod_disciplina)
    ON DELETE RESTRICT;
 
ALTER TABLE DISC_HIST ADD CONSTRAINT FK_DISC_HIST_2
    FOREIGN KEY (FK_HISTORICO_cod_historico)
    REFERENCES ??? (???);
 
ALTER TABLE CURSO_DISCIPLINA ADD CONSTRAINT FK_CURSO_DISCIPLINA_1
    FOREIGN KEY (FK_CURSO_cod_curso)
    REFERENCES CURSO (cod_curso)
    ON DELETE RESTRICT;
 
ALTER TABLE CURSO_DISCIPLINA ADD CONSTRAINT FK_CURSO_DISCIPLINA_2
    FOREIGN KEY (FK_DISCIPLINA_cod_disciplina)
    REFERENCES DISCIPLINA (cod_disciplina)
    ON DELETE RESTRICT;
 
ALTER TABLE ALUNO_DISCP ADD CONSTRAINT FK_ALUNO_DISCP_1
    FOREIGN KEY (FK_DISCIPLINA_cod_disciplina)
    REFERENCES DISCIPLINA (cod_disciplina)
    ON DELETE RESTRICT;
 
ALTER TABLE ALUNO_DISCP ADD CONSTRAINT FK_ALUNO_DISCP_2
    FOREIGN KEY (FK_ALUNO_HISTORICO_RA, FK_ALUNO_HISTORICO_cod_historico???)
    REFERENCES ALUNO (RA, ???)
    ON DELETE RESTRICT;
 
ALTER TABLE HISTORICO ADD CONSTRAINT FK_HISTORICO_2
    FOREIGN KEY (RA???)
    REFERENCES ??? (???);
 
ALTER TABLE DEPENDE ADD CONSTRAINT FK_DEPENDE_1
    FOREIGN KEY (fk_DISCIPLINA_cod_disciplina)
    REFERENCES DISCIPLINA (cod_disciplina)
    ON DELETE CASCADE;
 
ALTER TABLE DEPENDE ADD CONSTRAINT FK_DEPENDE_2
    FOREIGN KEY (fk_DISCIPLINA_cod_disciplina_)
    REFERENCES DISCIPLINA (cod_disciplina)
    ON DELETE CASCADE;
 
ALTER TABLE TEL_ALUNO ADD CONSTRAINT FK_TEL_ALUNO_2
    FOREIGN KEY (RA???)
    REFERENCES ??? (???);
 
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_2
    FOREIGN KEY (RA???)
    REFERENCES ??? (???);
 
ALTER TABLE ALUNO_TEL ADD CONSTRAINT FK_ALUNO_TEL_2
    FOREIGN KEY (cod_tel_alunos???, RA???)
    REFERENCES ??? (???);